CREATE TABLE public.ingredient (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    recipe_id integer,
    diet text NOT NULL,
    CONSTRAINT ingredient_pkey PRIMARY KEY (id),
    CONSTRAINT ingredient_name_key UNIQUE (name),
    CONSTRAINT diet_constraint CHECK ((diet = ANY (ARRAY['vegan'::text, 'vegetarian'::text, 'fish'::text, 'meat'::text])))
);

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) ON UPDATE CASCADE ON DELETE SET NULL;
