CREATE TABLE public.recipe (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    name text NOT NULL,
    description text,
    image text,
    steps jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id text,
    cook_time interval,
    prep_time interval,
    portions integer NOT NULL,
    diet text NOT NULL,
    CONSTRAINT recipe_pkey PRIMARY KEY (id)
);

CREATE TRIGGER set_public_recipe_updated_at BEFORE UPDATE ON public.recipe FOR EACH ROW EXECUTE FUNCTION public.set_current_timestamp_updated_at();
