CREATE TABLE public.recipe_ingredient (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    recipe_id integer NOT NULL,
    ingredient_id integer NOT NULL,
    amount real NOT NULL,
    unit integer DEFAULT 1 NOT NULL,
    index integer DEFAULT 0 NOT NULL,
    section text,
    extra_info text,
    CONSTRAINT recipe_ingredient_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_ingredient_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT recipe_ingredient_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipe(id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT recipe_ingredient_unit_fkey FOREIGN KEY (unit) REFERENCES public.unit(id) ON UPDATE RESTRICT ON DELETE RESTRICT
);
